apiVersion: v1
kind: Service
metadata:
  name: job-logger
spec:
  selector:
    app: job-logger
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: job-logger
  name: job-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-logger
  template:
    metadata:
      labels:
        app: job-logger
    spec:
      containers:
        - name: job-logger
          image: mikejoh/job-logger:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

