apiVersion: batch/v1
kind: Job
metadata:
  name: job-sender-parallell
spec:
  completions: 10           # number of times to run
  parallelism: 2            # number of pods that can run in parallel
  backoffLimit: 2           # number of retries before throwing error
  activeDeadlineSeconds: 10 # time to allow job to run
  template:
    metadata:
      labels:
        app: job-sender
    spec:
      restartPolicy: OnFailure
      containers:
        - name: job
          image: mikejoh/job-sender:latest
          env:
            - name: LOG_ENDPOINT
              value: http://job-logger.default.svc.cluster.local
            - name: JOB_TYPE
              value: parallell
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name